services:
  postgres:
    image: postgres:15
    container_name: postgres_forecast
    environment:
      POSTGRES_USER: forecast_user
      POSTGRES_PASSWORD: forecast_pass
      POSTGRES_DB: forecast_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: